services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]
      restart: always

  ignite:
    image: apacheignite/ignite:latest
    ports:
      - "10800:10800"  # Ignite thin client port
      - "47100:47100"  # Communication SPI port
      - "47500-47509:47500-47509"  # Discovery SPI ports
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-spring
    restart: always

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"  # Default port for Cassandra CQL
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: 256
    restart: always

  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"  # Etcd client communication port
      - "2380:2380"  # Etcd peer communication port
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    restart: always

  couchbase:
    image: couchbase:latest
    ports:
      - "8091-8094:8091-8094"  # Couchbase web console, REST API, and query services
      - "11210:11210"  # Couchbase data service port
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=my_bucket  # Create a default bucket
    restart: always

  robotic-arm-service:
    image: robotic-arm-service
    build:
      context: ./RoboticArm  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (adjust if different)
    depends_on:
      - taskcoordinator
    ports:
      - "8080:80"  # Adjust the port mapping as needed
    environment:
      KAFKA_BROKER: kafka:9092
    restart: always

  taskcoordinator:
    build:
      context: ./CentralComponent/TaskCoordinatorService
      dockerfile: Dockerfile
    image: taskcoordinatorservice:latest
    container_name: taskcoordinatorservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"   # Map HTTP port for web traffic
      - "5005:5005" # Map debugging port
    depends_on:
      - kafka
    networks:
      - mynetwork
    command: ["dotnet", "TaskCoordinatorService.dll", "--urls", "http://0.0.0.0:80"]

  monitoring:
    build:
      context: ./CentralComponent/MonitoringService
      dockerfile: Dockerfile
    image: monitoringservice:latest
    container_name: monitoringservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"   # Map HTTP port for web traffic
      - "5006:5005" # Map debugging port
    depends_on:
      - taskcoordinator
    networks:
      - mynetwork
    command: ["dotnet", "MonitoringService.dll", "--urls", "http://0.0.0.0:80"]

  event-handler-service:
    image: event-handler-service
    build:
      context: ./CentralComponent/EventHandlerService  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (adjust if different)
    depends_on:
      - taskcoordinator
    ports:
      - "8081:80"  # Adjust the port mapping as needed
    environment:
      KAFKA_BROKER: kafka:9092
    restart: always

  storage-middleware-api:
    image: storage-middleware-api
    build:
      context: ./StorageMiddlewareApi
      dockerfile: Dockerfile
    depends_on:
      - redis
      - ignite
      - cassandra
      - etcd
      - couchbase
    ports:
      - "7000:80"
    restart: always
    environment:
      SELECTED_PERSISTED_STORAGE: cassandra
      SELECTED_CACHE_STORAGE: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IGNITE_HOST: ignite
      IGNITE_PORT: 10800
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      ETCD_HOST: etcd
      ETCD_PORT: 2379
      COUCHBASE_HOST: couchbase
      COUCHBASE_PORT: 8091
      COUCHBASE_USERNAME: Administrator
      COUCHBASE_PASSWORD: password