services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]
      restart: always

  ignite:
    image: apacheignite/ignite:latest
    ports:
      - "10800:10800"  # Ignite thin client port
      - "47100:47100"  # Communication SPI port
      - "47500-47509:47500-47509"  # Discovery SPI ports
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-spring
    restart: always

  robotic-arm-service:
    image: robotic-arm-service
    build:
      context: ./RoboticArm  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (adjust if different)
    depends_on:
      - kafka
    ports:
      - "8080:80"  # Adjust the port mapping as needed
    environment:
      KAFKA_BROKER: kafka:9092
    restart: always

  event-handler-service:
    image: event-handler-service
    build:
      context: ./CentralComponent/EventHandlerService  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (adjust if different)
    depends_on:
      - kafka
    ports:
      - "8081:80"  # Adjust the port mapping as needed
    environment:
      KAFKA_BROKER: kafka:9092
    restart: always

  storage-middleware-api:
    image: storage-middleware-api
    build:
      context: ./StorageMiddlewareApi
      dockerfile: Dockerfile
    depends_on:
      - redis
      - memcached
      - ignite
    ports:
      - "7000:80"
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      IGNITE_HOST: ignite
      IGNITE_PORT: 10800